[package]
name = "hamlex_os"
version = "0.1.0"
authors = ["nick_posix <top_secret>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
